# Form implementation generated from reading ui file 'Login.ui' 
# 
# Created by: PyQt6 UI code generator 6.4.2 
# 
# WARNING: Any manual changes made to this file will be lost when pyuic6 is 
# run again.  Do not edit this file unless you know what you are doing. 


from PyQt6 import QtCore, QtGui, QtWidgets 
import json 


class Ui_login(QtWidgets.QMainWindow): 
    def init(self): 
        super().init() 
        self.resize(342, 357) 
        self.Login = QtWidgets.QWidget() 
        self.UserName = QtWidgets.QLineEdit(parent=self.Login) 
        self.UserName.setGeometry(QtCore.QRect(10, 100, 321, 31)) 
        self.UserName.setObjectName("UserName") 
        self.Password = QtWidgets.QLineEdit(parent=self.Login) 
        self.Password.setGeometry(QtCore.QRect(10, 180, 321, 31)) 
        self.Password.setObjectName("Password") 
        self.pushButton = QtWidgets.QPushButton(parent=self.Login) 
        self.pushButton.setGeometry(QtCore.QRect(90, 270, 151, 51)) 
        self.pushButton.setObjectName("pushButton") 
        self.pushButton.clicked.connect(self.Login_B) 
        self.Sign_Up = QtWidgets.QPushButton(parent=self.Login) 
        self.Sign_Up.setGeometry(QtCore.QRect(60, 270, 100, 51)) 
        self.Sign_Up.setObjectName("Sign_Up") 
        self.Sign_Up.setHidden(True) 
        self.Sign_Up.setText("Sign_Up") 
        self.label = QtWidgets.QLabel(parent=self.Login) 
        self.label.setGeometry(QtCore.QRect(60, 20, 221, 31)) 
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter) 
        self.label.setObjectName("label") 
        self.setCentralWidget(self.Login) 
        self.label_2 = QtWidgets.QLabel(parent=self.Login) 
        self.label_2.setGeometry(QtCore.QRect(20, 100, 1, 1)) 
        font = QtGui.QFont() 
        font.setPointSize(12) 
        self.label_2.setFont(font) 
        self.label_2.setStyleSheet("color:red") 
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter) 
        self.label_2.setObjectName("label_2") 
        self.EROR2 = QtWidgets.QLabel(parent=self.Login) 
        self.EROR2.setGeometry(QtCore.QRect(20, 180, 1, 1)) 
        font = QtGui.QFont() 
        font.setPointSize(12) 
        self.EROR2.setFont(font) 
        self.EROR2.setStyleSheet("color:red") 
        self.EROR2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter) 
        self.EROR2.setObjectName("EROR2") 
        self.setCentralWidget(self.Login) 
         
        self.label_2.setText(("Password Or UserName Is Wrong!")) 
        self.EROR2.setText(("Password Or UserName Is Wrong!")) 
        self.label_2.setGeometry(QtCore.QRect(20, 100, 301, 31)) 
        self.EROR2.setGeometry(QtCore.QRect(20, 180, 301, 31)) 
        self.label_2.setHidden(True) 
        self.EROR2.setHidden(True) 
        self.w = None 
        self.x = None 

        self.pushButton.setText("LOGIN") 
        self.label.setText("WELLCOME") 
    # def retranslateUi(self, Jax): 
    #     _translate = QtCore.QCoreApplication.translate 
    #     Jax.setWindowTitle(_translate("Jax", "MainWindow")) 
         

    def Login_B(self): 
        User = self.UserName.text() 
        Pass = self.Password.text() 
        with open("Save.json", mode="r") as file: 
            load = json.load(file) 
        Log = False 
        for i in load:     
            if User == i["UserN"] and Pass == i["Password"]: 
                print("WELLCOME BACK!") 
                Log=True 
                if self.x is None: 
                    self.x = Dashboard() 
                self.x.show() 
                break 
        if Log == False: 
            self.UserName.setText("") 
            self.Password.setText("") 
            self.Sign_Up.setHidden(False) 
            self.label_2.setHidden(False) 
            self.EROR2.setHidden(False)

self.pushButton.setGeometry(QtCore.QRect(170, 270, 100, 51)) 
            self.pushButton.clicked.connect(self.Login_C) 
        self.Sign_Up.clicked.connect(self.SignUp) 
        self.pushButton.setText("Try Again") 
    def Login_C(self):  
        self.label_2.setHidden(True) 
        self.EROR2.setHidden(True) 
        self.pushButton.setText("Login") 
        self.pushButton.clicked.connect(self.Login_B) 

    def SignUp(self): 
         

        if self.w is None: 
            self.w = Ui_Sign_Up() 
        self.w.show() 

class Ui_Sign_Up(QtWidgets.QWidget): 
    def init(self): 
        super().init() 
        centeralwidget = QtWidgets.QVBoxLayout() 
        self.pushButton = QtWidgets.QPushButton() 
        self.pushButton.setGeometry(QtCore.QRect(100, 270, 151, 51)) 
        self.pushButton.setObjectName("pushButton") 
        self.pushButton.clicked.connect(self.Sign_Up) 
        self.UserName = QtWidgets.QLineEdit() 
        self.UserName.setEnabled(True) 
        self.UserName.setGeometry(QtCore.QRect(10, 60, 321, 31)) 
        self.UserName.setObjectName("UserName") 
        self.UserName.setPlaceholderText("Write Your User Name") 
        self.label = QtWidgets.QLabel() 
        self.label.setGeometry(QtCore.QRect(60, 9, 221, 31)) 
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter) 
        self.label.setObjectName("label") 
        self.Password = QtWidgets.QLineEdit() 
        self.Password.setEnabled(True) 
        self.Password.setGeometry(QtCore.QRect(10, 130, 321, 31)) 
        self.Password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal) 
        self.Password.setObjectName("Password") 
        self.Password.setPlaceholderText("Write Password") 
        self.RePassword = QtWidgets.QLineEdit() 
        self.RePassword.setEnabled(True) 
        self.RePassword.setGeometry(QtCore.QRect(10, 200, 321, 31)) 
        self.RePassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password) 
        self.RePassword.setObjectName("RePassword") 
        self.RePassword.setPlaceholderText("Write Password Again") 
        self.label = QtWidgets.QLabel() 
        self.label.setGeometry(QtCore.QRect(60, 9, 221, 31)) 
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter) 
        self.label.setObjectName("label") 

        self.pushButton.setText("Sign-Up") 
        self.label.setText( "WELLCOME") 
        centeralwidget.addWidget(self.label) 
        centeralwidget.addWidget(self.UserName) 
        centeralwidget.addWidget(self.Password) 
        centeralwidget.addWidget(self.RePassword) 
        centeralwidget.addWidget(self.pushButton) 
        self.setLayout(centeralwidget) 

        # self.retranslateUi(Sign_UP) 
        # QtCore.QMetaObject.connectSlotsByName(Sign_UP) 

    def Sign_Up(self): 
         
        UserName = self.UserName.text() 
        Password = self.Password.text() 
        RePassword = self.RePassword.text() 
         

        SAVEdict = { 
            "UserN" : UserName, 
            "Password" : Password, 
            "RePassword" : RePassword 
        } 
        with open("Save.json", mode="r") as file: 
            load = json.load(file)     
        TUNAME= False 
        if UserName != "" and Password != "": 
            for i in load:     
                if UserName == i["UserN"]: 
                    TUNAME = True 
            if Password == RePassword and TUNAME == False : 
                with open("Save.json", mode="r") as file: 
                    List = json.load(file) 
                    List.append(SAVEdict) 
                file = open("Save.json", mode="w") 
                json.dump(List ,file) 
                self.close() 
            else : 
                self.UserName.setText("UserName In Already Taket") 
                self.RePassword.setText("")

self.Password.setText("") 
                self.Password.setPlaceholderText("Password And RePassword Aren't Same!") 
        else: 
            print("Inputs Shouldn't Be Empty!") 
class Dashboard(QtWidgets.QWidget): 
    def init(self): 
        super().init() 
        centeralwidget = QtWidgets.QVBoxLayout()  
        self.label = QtWidgets.QLabel() 
        self.label.setGeometry(QtCore.QRect(60, 9, 221, 31)) 
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter) 
        self.label.setObjectName("label") 
        self.label.setText("Wellcome!") 
        self.RPBTN = QtWidgets.QPushButton() 
        self.RPBTN.setGeometry(QtCore.QRect(100, 270, 151, 51)) 
        self.RPBTN.setObjectName("RPBTN") 
        self.RPBTN.clicked.connect(self.ResetPass) 
        centeralwidget.addWidget(self.label) 
        centeralwidget.addWidget(self.RPBTN) 
        self.setLayout(centeralwidget) 
        self.S=None 
    def ResetPass(self): 
        if self.S is None: 
            self.S = Reset_Password() 
        self.S.show() 

class Reset_Password(QtWidgets.QWidget): 
    def init(self): 
        super().init() 
        centeralwidget = QtWidgets.QVBoxLayout() 
        self.pushButton = QtWidgets.QPushButton() 
        self.pushButton.setGeometry(QtCore.QRect(100, 270, 151, 51)) 
        self.pushButton.setObjectName("pushButton") 
        self.UserName = QtWidgets.QLineEdit() 
        self.UserName.setEnabled(True) 
        self.UserName.setGeometry(QtCore.QRect(10, 60, 321, 31)) 
        self.UserName.setObjectName("UserName") 
        self.UserName.setPlaceholderText("Write Your User Name") 
        self.label = QtWidgets.QLabel() 
        self.label.setGeometry(QtCore.QRect(60, 9, 221, 31)) 
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter) 
        self.label.setObjectName("label") 
        self.Password = QtWidgets.QLineEdit() 
        self.Password.setEnabled(True) 
        self.Password.setGeometry(QtCore.QRect(10, 130, 321, 31)) 
        self.Password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal) 
        self.Password.setObjectName("Password") 
        self.Password.setPlaceholderText("Write Password") 
        self.RePassword = QtWidgets.QLineEdit() 
        self.RePassword.setEnabled(True) 
        self.RePassword.setGeometry(QtCore.QRect(10, 200, 321, 31)) 
        self.RePassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password) 
        self.RePassword.setObjectName("RePassword") 
        self.RePassword.setPlaceholderText("Write Password Again") 
        self.label = QtWidgets.QLabel() 
        self.label.setGeometry(QtCore.QRect(60, 9, 221, 31)) 
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter) 
        self.label.setObjectName("label") 

        self.pushButton.setText("Sign-Up") 
        self.label.setText( "WELLCOME") 
        centeralwidget.addWidget(self.label) 
        centeralwidget.addWidget(self.UserName) 
        centeralwidget.addWidget(self.Password) 
        centeralwidget.addWidget(self.RePassword) 
        centeralwidget.addWidget(self.pushButton) 
        self.setLayout(centeralwidget) 
         
if name == "main": 
    import sys 
    app = QtWidgets.QApplication(sys.argv) 

    ui = Ui_login() 
    ui.show() 
     
    sys.exit(app.exec())
